templates:
  - name: Circuit Presenter + Compose UI
    file_name_suffix: Screen

  - name: Circuit Presenter + Compose UI.child.0
    file_name_suffix: PresenterTest

  - name: Circuit Presenter + Compose UI.child.1
    file_name_suffix: UiTest

  - name: Circuit Presenter + Compose UI.child.2
    file_name_suffix: Presenter

  - name: Circuit Presenter + Compose UI.child.3
    file_name_suffix: Ui

  - name: Circuit Presenter (without UI)
    file_name_suffix: Screen

  - name: Circuit Presenter (without UI).child.0
    file_name_suffix: PresenterTest

  - name: Circuit Presenter (without UI).child.2
    file_name_suffix: Presenter

  - name: UdfViewModel convert
    file_name_suffix: Screen

  - name: UdfViewModel convert.child.0
    file_name_suffix: ViewModel